name: CNF Torch
dataset:
  batch_size: 32
  train_samples: 10000
  val_samples: 1000
  test_samples: 1000
model:
  input_shape: [2]
  vector_field:
    input_dim: 2
    freqs: 3
    neurons_per_layer:
      - 64
      - 64
      - 2
    activations:
      - gelu
      - gelu
      - gelu
  max_epochs: 10
mlflow_config:
  experiment_name: Trace Comparison
  tracking_uri: file:///home/lucasbanunes/workspaces/even-flow-pearl-jam.mp3/tests/data/mlruns
